export const data = {
  products: [
    {
      id: 1,
      name: "Lenovo Stylus 340",
      category: "Notebooks",
      image: "/images/p1.jpg",
      price: "55000",
      brand: "Lenovo",
      rating: 4.5,
      numReviews: 10,
      description:
        "High quality of product and create for work it´s not a notebook gamer",
    },
    {
      id: 2,
      name: "Logitech 2500",
      category: "Mouses",
      image: "/images/p2.webp",
      price: "6850",
      brand: "Logitech",
      rating: 4,
      numReviews: 7,
      description: "Mouse gamer created for more confortability",
    },
    {
      id: 3,
      name: "Notebook Exo",
      category: "Notebooks",
      image: "/images/p3.png",
      price: "55650",
      brand: "Exo",
      rating: 3.5,
      numReviews: 5,
      description: "Notebook create for work in office",
    },
    {
      id: 4,
      name: "Macbook pro i7 10910",
      category: "Notebook",
      image: "/images/p4.jpg",
      price: "112000",
      brand: "Apple",
      rating: 4.8,
      numReviews: 11,
      description: "Macbook pro for the best design and general work",
    },
    {
      id: 5,
      name: "Notebook hp slim & Touchable",
      category: "Notebooks",
      image: "/images/p5.jpg",
      price: "98500",
      brand: "HP",
      rating: 4.3,
      numReviews: 9,
      description: "Notebook for office and play games with the touch panel",
    },
  ],
};
